#!/bin/bash
#PBS -N 01_process_radtags_pstI_mspI
#PBS -l select=1:ncpus=16
#PBS -l walltime=24:00:00
#PBS -m e
#PBS -M 25405942@sun.ac.za

cd $PBS_O_WORKDIR

module load app/stacks/2.68

process_radtags \
-1 ~/ch2/00_data/CGBSLL120344/P01_S34_L008_R1_001.fastq.gz \
-2 ~/ch2/00_data/CGBSLL120344/P01_S34_L008_R2_001.fastq.gz \
-o ~/ch2/00_samples/pstI_mspI \
-b ~/ch2/00_data/CGBSLL120344/GBS_barcodes.193-288_no_line_1.txt \
--renz_1 pstI --renz_2 mspI \
-r -c -q --score-limit 20 \
&> ~/ch2/00_samples/pstI_mspI/01_process_radtags_pstI_mspI.oe

