#!/bin/bash
#PBS -N 04_fst_outlier_03_fold_CC_LB_02_month
#PBS -l select=1:ncpus=4:mem=4GB
#PBS -l walltime=744:00:00
#PBS -m e
#PBS -M 25405942@sun.ac.za

# Load ANGSD module
module load app/angsd/0.940

mkdir -p ~/ch2/03_angsd/fst/

# Calculate population pairwise fst 

# CC vs LB
realSFS fst index \
  ~/ch2/03_angsd/sfs/03_angsd_saf_CC_02.saf.idx \
  ~/ch2/03_angsd/sfs/03_angsd_saf_LB_02.saf.idx \
  -sfs ~/ch2/03_angsd/sfs/CC_LB_02.ml \
  -fold 1 \
  -fstout ~/ch2/03_angsd/fst/CC_LB_02
