#!/bin/bash
#PBS -N 05_fastsimcoal_param_est_bootstrap_1PopBot25_1
#PBS -l select=1:ncpus=16:mem=16GB
#PBS -l walltime=24:00:00
#PBS -m e
#PBS -M 25405942@sun.ac.za

FOUNDATION=~/software/fastsimcoal/bottleneck_gla_anc
BASE=~/software/fastsimcoal/bottleneck_gla_anc/1PopBot25
BOOTBASE=$BASE/1PopBot25_boot

for i in {1..25}
do
    BOOTDIR=$BOOTBASE/1PopBot25_boot_$i

    echo "Processing $BOOTDIR"

    # copy tpl and est
    cp $FOUNDATION/1PopBot25.tpl $BOOTDIR/1PopBot25_boot.tpl
    cp $FOUNDATION/1PopBot25.est $BOOTDIR/1PopBot25_boot.est

    # go into boot directory
    cd $BOOTDIR

    # run Fastsimcoal
    ~/software/fastsimcoal/bottleneck_gla_anc/fsc28 \
        -t 1PopBot25_boot.tpl \
        -e 1PopBot25_boot.est \
        --initvalues $BASE/1PopBot25.pv \
        -d -M -n100000 -L20 -z0.01 -y 3 -c16
done

