#!/bin/bash
#PBS -N 05_fastsimcoal_parabootstrapSFS_1PopBot19
#PBS -l select=1:ncpus=32:mem=32GB
#PBS -l walltime=24:00:00
#PBS -m e
#PBS -M 25405942@sun.ac.za

cd $PBS_O_WORKDIR

cd ~/software/fastsimcoal/bottleneck/1PopBot19
~/software/fastsimcoal/bottleneck/fsc28 -i 1PopBot19_boot.par -n100 -j -d -s0 -x –I -q -c32