#!/bin/bash
#PBS -N 05_fastsimcoal_bottleneck_gla_anc5
#PBS -l select=1:ncpus=8:mem=8GB
#PBS -l walltime=24:00:00
#PBS -m e
#PBS -M 25405942@sun.ac.za

cd $PBS_O_WORKDIR
cd ~/software/fastsimcoal/bottleneck_gla_anc

./fsc28 -t 1PopBot5.tpl -e 1PopBot5.est -d -M -n100000 -L20 -c8 -q --seed 56789 -z0.01 -y 3 
