#!/bin/bash
#PBS -N 05_fastsimcoal_stable_gla4
#PBS -l select=1:ncpus=8:mem=8GB
#PBS -l walltime=24:00:00
#PBS -m e
#PBS -M 25405942@sun.ac.za

cd $PBS_O_WORKDIR
cd ~/software/fastsimcoal/stable_gla

./fsc28 -t 1PopStab4.tpl -e 1PopStab4.est -d -M -n100000 -L20 -c8 -q --seed 45678 -z0.01 -y 3 
