#!/bin/bash
#PBS -N 05_fastsimcoal_parabootstrapSFS_1PopBot24
#PBS -l select=1:ncpus=32:mem=32GB
#PBS -l walltime=24:00:00
#PBS -m e
#PBS -M 25405942@sun.ac.za

cd $PBS_O_WORKDIR

cd ~/software/fastsimcoal/bottleneck_gla/1PopBot24
~/software/fastsimcoal/bottleneck_gla/fsc28 -i 1PopBot24_boot.par -n100 -j -d -s0 -x –I -q -c32
