#!/bin/bash
#PBS -N 05_fastsimcoal_bottleneck
#PBS -l select=1:ncpus=8:mem=8GB
#PBS -l walltime=24:00:00
#PBS -m e
#PBS -M 25405942@sun.ac.za

cd $PBS_O_WORKDIR
cd ~/software/fastsimcoal/bottleneck

./fsc28 -t 1PopBot.tpl -e 1PopBot.est -d -M -n1000000 -L20 -c8 -q --seed 12345 -z0.01 -y 3 
